- myhpi/settings.py
- myhpi/static/css/myHPI_admin.css
- myhpi/wagtail_markdown/static/wagtail_markdown/js/easymde.attach.js
In https://github.com/fsr-de/1327 there is also an icon for adding emojis - Do you think we want this again? I have the feeling it was not used...
> Add document toolbar icons

- .env.example
- myhpi/core/auth.py
- myhpi/core/urls.py
- myhpi/settings.py
- myhpi/templates/login.html
- myhpi/urls.py
- poetry.lock
- pyproject.toml
> Add OIDC login

- myhpi/core/models.py
> Set group widget to Select for MinutesList

- myhpi/core/models.py
Closes #78 (Apart from the first point, which should be a separate issue)
> Minutes convenience functions

- myhpi/core/models.py
- myhpi/settings.py
- myhpi/urls.py
- poetry.lock
- pyproject.toml
> Add select2 field for selection of minutes participants

- README.md
Starting with poetry 1.1.7 poetry got a new install link which is now also in our readme.
> New Poetry link

- myhpi/polls/migrations/0001_initial.py
- myhpi/polls/migrations/0008_polllist.py
- myhpi/polls/models.py
Closes #122 
Since it changes migrations, this requires a new db
> Make polls, polllists BasePages

- myhpi/core/models.py
> Remove duplicate minutes from visible minutes

- myhpi/core/templates/core/label.html
- myhpi/core/templates/core/minutes.html
- myhpi/core/templates/core/minutes_list.html
> Add labels to minutes

- myhpi/core/models.py
> Make BasePage not creatable

- poetry.lock
- pyproject.toml
> Fix markdown to 3.3.7, update dependencies

- install-bootstrap.py
> Fix bootstrap installation to version 5.0.2

- README.md
- myhpi/settings.py
This will remove a warning caused by the debug toolbar update the poetry install link in the README.
> Fix Debug Toolbar Warning (#118)

- README.md
- myhpi/static/scss/navbar.scss
- myhpi/templates/base.html
- myhpi/templates/nav_level.html
Please note: The logout button has no function as of now.
> fix: Warning messages for SVG dimensions

- myhpi/core/wagtail_hooks.py
- myhpi/tests/core/test_view_permissions.py
- myhpi/tests/core/utils.py
> Enable super user to view all pages

- myhpi/search/templates/search/search.html
- myhpi/search/templates/search/search_field.html
- myhpi/search/templates/search/search_result.html
- myhpi/search/views.py
- myhpi/static/js/myHPI.js
- myhpi/static/js/search.js
- myhpi/static/scss/myHPI.scss
- myhpi/templates/base.html
- Adds a search button to the navbar
- Improves design of search page
1. How to internationalise the search page?
2. (Under which circumstances) Will the `result.search_description` in `search_result.html` be set?
3. Search is a separate module: Is there a way (and is it preferred) to make the `search.js` and the search button popup in `base.html` part of the module?
> Add search button

- myhpi/core/migrations/0001_initial.py
- myhpi/core/migrations/0003_minutes_guests_alter_informationpage_body_and_more.py
- myhpi/core/models.py
- myhpi/core/templates/core/minutes.html
- myhpi/search/templates/search/search_result.html
- myhpi/tests/core/setup.py
> Rename text to body on minutes

- uwsgi.ini
accidentally moved to the configuration repo, but is needed inside the container
> add uwsgi.ini

- myhpi/static/scss/footer.scss
> fix: Match SCSS to decreased markdown levels in footer title

- myhpi/core/templates/core/information_page.html
- myhpi/core/templates/core/minutes.html
- myhpi/core/templates/core/minutes_list.html
- myhpi/locale/de/LC_MESSAGES/django.po
- myhpi/polls/templates/polls/poll.html
- myhpi/search/templates/search/search.html
- myhpi/search/templates/search/search_field.html
- myhpi/settings.py
- myhpi/templates/404.html
- myhpi/templates/base.html
- myhpi/templates/login.html
- myhpi/tests/test_minutes_extensions.py
> Translate templates

- myhpi/core/context.py
- myhpi/core/templatetags/core_extras.py
- myhpi/static/scss/myHPI.scss
- myhpi/static/scss/navbar.scss
- myhpi/templates/base.html
- myhpi/templates/nav_level.html
- myhpi/tests/core/setup.py
- myhpi/tests/core/test_menu.py
- myhpi/tests/core/test_redirect_menu_item.py
- myhpi/tests/core/utils.py
Close #280 close #279 close #278 close #277 close #276
> Minor Improvements and Fixes

- .gitignore
- myhpi/settings.py
> Write logs into log file

- myhpi/core/wagtail_hooks.py
- myhpi/settings.py
> change wagtail document serving method to serve_view

- myhpi/core/models.py
- myhpi/locale/de/LC_MESSAGES/django.po
- myhpi/search/templates/search/search.html
Fixes #324 
Run `python manage.py update_index` once.
> Fix search in minutes

- myhpi/locale/de/LC_MESSAGES/django.po
- myhpi/templates/403.html
> add 403 template

- myhpi/templates/base.html
> Redirect to current page when signing in

- myhpi/core/context.py
- myhpi/core/middleware.py
- myhpi/core/utils.py
- myhpi/core/wagtail_hooks.py
- myhpi/templates/base.html
- myhpi/tests/core/test_menu.py
May reduce page loading performance by half. Will see in production.
see #328
> Improve performance of generating menu

- myhpi/core/markdown/extensions.py
- myhpi/static/js/admin/easymde_custom.js
- myhpi/static/scss/myHPI.scss
> use proper image rendering instead of preview

- myhpi/core/models.py
- myhpi/core/templates/core/minutes_list.html
> display minute draft in minutes list for users in that group

- myhpi/core/context.py
- myhpi/core/templatetags/core_extras.py
- myhpi/locale/de/LC_MESSAGES/django.po
- myhpi/static/scss/myHPI.scss
- myhpi/templates/base.html
Closes #99 
~~Not really happy with the styling.~~
> Add minutes shortcut

- myhpi/core/models.py
- myhpi/core/templates/core/minutes_list.html
> Fix date of minutes entry having a wrong URL if minute is a draft

- myhpi/core/templatetags/minutes_tags.py
> fix minute navigation for unsaved minutes

- Dockerfile
When building locally with this change the version is 1.0.1 for me (and was 0.0.0 before)
> Add dynamic versioning to Dockerfile

- .github/workflows/build-container.yml
- Dockerfile
> Add checkout to docker build action for git context

- myhpi/core/templates/core/information_page.html
- myhpi/core/templates/core/minutes.html
- myhpi/core/templatetags/core_extras.py
> Open external links in another tab and add icon showing that it's an external link

- myhpi/core/templates/core/minutes.html
- myhpi/static/scss/myHPI.scss
- myhpi/templates/base.html
- myhpi/tests/core/test_minutes.py
> Improve visuals of minute previous and next buttons

- myhpi/polls/models.py
just noticed that I reverted this change in the model although it is part of the migration, so django complains about changed models. No impact for any data
> fix model mismatch with migration

- myhpi/core/context.py
- myhpi/templates/base.html
> Disable menu cache when in debug mode

- myhpi/core/templatetags/core_extras.py
> Do not treat section links as external

- myhpi/core/models.py
- myhpi/core/wagtail_hooks.py
- myhpi/polls/wagtail_hooks.py
> Check for view permissions when serving polls

- myhpi/locale/de/LC_MESSAGES/django.po
- myhpi/templates/base.html
Adds a button that links to the keycloak account console. 
Closes #540
> Add "Edit profile" button

- myhpi/templates/base.html
Close #589 
Close #341 (replace)
> Force footer to bottom of viewport

- .github/workflows/tests.yml
- myhpi/core/templatetags/minutes_tags.py
Fixes #427, see also https://github.com/fsr-de/myHPI/pull/446
> Fix minutes preview raising Exception

- .github/workflows/tests.yml
This bug was introduced in #489.
> Fix coverage report being skipped in CI

- myhpi/locale/de/LC_MESSAGES/django.po
- myhpi/templates/base.html
- myhpi/tenca_django/templates/tenca_django/action.html
- myhpi/tenca_django/templates/tenca_django/dashboard.html
- myhpi/tenca_django/templates/tenca_django/delete_list.html
- myhpi/tenca_django/templates/tenca_django/manage_list.html
- myhpi/tenca_django/templates/tenca_django/manage_subscription.html
- myhpi/tenca_django/templates/tenca_django/report.html
> Improve layout and fix translations for mailing lists
