fsr-de/myHPI

myhpi/core/auth.py
myhpi/core/urls.py

Fixing some possible errors or vulnerabilities if someone has "student" or "uni-potsdam." in their email address.
Changes to urls.py was done by automatic linting.

Improve string handling in auth.py

---

.github/workflows/tests.yml
myhpi/wagtail_markdown/minutes_extensions.py
tests/test_minutes_extensions.py

Support any character in enter, leave commands (and make tests work)

---

myhpi/core/templates/core/minutes.html
myhpi/static/css/myHPI.css
myhpi/static/js/print_processor.js

Closes #66, #69 and implements better handling for links (numbers and a list at the bottom of the page) and abbreviations (expands them).
There is still a remaining problem. When only one link is present, the rendering breaks on Firefox for unknown reasons. It works with multiple links on Firefox, it works with one or more links on Chromium, I have only observed this one weird case. We need to decide if that is ok, since it is only one edge case, if we should display a warning in that one case or if that needs to be fixed, which I have no idea how to do.
Firefox correct:
Chromium correct:
Firefox incorrect with one link:
Chromium correct with one link:

Add post processing for printing minutes

---

myhpi/core/models.py
myhpi/core/templates/core/minutes_list.html
myhpi/static/css/myHPI.css

Closes #87.
Remaining issues:
- ~~Labels do not have an associated color, so the secondary color is used~~ -> moved to #95 
- ~~Font awesome icons are not yet available~~ -> Not entirely relevant for this PR since currently only one icon is needed
- ~~It is not clear what should be shown in the permissions field~~ -> See discussion on #87
- ~~There is no separation by years, since it does not seem immediately important~~ Done.

Add table for minute list

---

myhpi/core/migrations/0002_minutes.py
myhpi/core/models.py
myhpi/settings.py

Closes #33 
Significant change: Users can not be deleted if they are referenced by minutes

Remove warnings from migrations

---

.github/workflows/dependabot-assign.yml

Will auto-assign reviewers of the "myhpi-dependencies" group to dependabot PRs.

Auto assign reviewers for dependabot PRs

---

.github/workflows/dependabot-assign.yml

Since #106 didn't work with the reviewer team, as seen in #110, this should work (at least it has before).

Explicitly assign reviewer for dependabot PRs

---

myhpi/core/models.py

Probably introduced through a merge.

Remove double entries in InformationPage

---

myhpi/static/scss/navbar.scss
myhpi/templates/base.html

Should be working now (testing it in depth is cumbersome for me, as I'd have to create loads of pages manually/duplicate nodes in DOM)

fix: Make menu scrollable on Desktop

---

myhpi/core/markdown/extensions.py

closes #45 
There is one small issue left with the current solution: a heading of level 6 is still matched by the regex, as there are 5 hashtags in it. This means that one is left with a result of `<h6># Text</h6>`. The smoother solution would be to not replace the line at all, but I can't come up with a regex that does so. As nobody actually uses h6 anyways, I think thats not such a big issue

add Markdown preprocessor to decrease heading level

---

.pre-commit-config.yaml
poetry.lock

#241 is not yet possible as poetry when run locally refuses to yet update to 2.0.0 but rather to 1.7.8 only. The error message when trying to update to 2.0.0 can be seen in the runner of #241

Bump autoflake to 1.7.8

---

.github/workflows/tests.yml

Our pipeline currently fails as the lock files of version 1.3 of poetry are not compatible with the old logfiles [see changelog](https://github.com/python-poetry/poetry/blob/master/CHANGELOG.md) .

Update poetry to version 1.3

---

README.md
myhpi/core/models.py
myhpi/core/templates/core/information_page.html
myhpi/locale/de/LC_MESSAGES/django.po

Use firstname lastname for last edited by

---

myhpi/static/security.txt
myhpi/urls.py

See https://securitytxt.org/
Closes #409

Add .well-known/security.txt

---

myhpi/core/models.py

On my machine fixes the error that I found when no participants in a minute are preselected
[Here](https://select2.org/appearance#container-width) I found more options in case we want to fix that in a global stylesheet.

Add style to minutes participant selection

---

myhpi/core/auth.py

Due to the migration, the claims contain changed usernames and email addresses. However, only the new email address was preserved.
Therefore, the account was not found during a second log in.

Hotfix: Update username to be able to log in a second time

---

myhpi/core/context.py

Closes #429 
This PR sorts the menus based on the `path` attribute of each page which represents the configured ordering in the admin interface.

Sort menu items in frontend

---

myhpi/core/markdown/utils.py

Closes #458
Trailing newlines are stripped from the markdown, thus needing two `\n` before appending the abbreviations.

Fix abbreviation rendering with table at the end

---

.github/workflows/build-container.yml

Once again for dynamic versioning. The current image has the version 0.0.0 because tags are not fetched when checking out. That should be solved with this PR.

Fetch tags to use dynamic versioning

---

.github/workflows/build-container.yml

Sadly #473 still did not fetch the tags, which I verified when I downloaded the image. This will fetch the entire commit history. We can see afterward if it works and slows down the action significantly.

Fetch entire history in docker action

---

myhpi/core/auth.py

The previous PR #422 prepared everything for the migration to Keycloak and used it as the IDP. 
As we have now migrated our group memberships to Keycloak, we can now update the myHPI groups from the data given in the OIDC tokens. 
This PR effectively only re-enables a disabled line of code. We have tested its functionality using a hotpatch in the production environment.

Fully enable Keycloak Group management

---

myhpi/core/templates/core/information_page.html
myhpi/core/templates/core/minutes.html
myhpi/core/templates/core/minutes_list.html
myhpi/core/templates/core/sidebar.html
myhpi/locale/de/LC_MESSAGES/django.po
myhpi/static/scss/myHPI.scss

Closes #353.
Furthermore, this PR streamlines the minute and information page sidebar layout (see second commit) and also adds empty date or editor handling.
**I was unable to test some of the changes, specifically those about the minute sidebar. Before approving, please check whether everything looks as expected.** I'm investigating why minute pages don't work (even on main) on my local setup.

Sidebar improvements

---

myhpi/core/models.py

When changing the value of these fields on a German page and synchronizing the translation, the change will be applied to the translation, too.
Closes #373

Make all `ParentalManyToManyFields` synchronized

---

myhpi/static/scss/myHPI.scss

Closes #483.
---
Further explanations:
- Relevant code is in myhpi/core/markdown/fields.py
- Specifically: `html2text` drops all css classes when converting html back to md
- Sadly, there is no quick workaround to get those classes back

Work around missing image class in translations bug

---

myhpi/static/js/admin/easymde_custom.js

Our custom markdown extensions only recognize time strings in German locale. Therefore, this PR enforces German locale for timestamps added to minutes by the buttons in the editor.
Closes #359

Enforce german locale for time strings in markdown

---

myhpi/core/markdown/fields.py

Set maximum line length to 0 so headings won't be truncated.
Closes #510

Don't wrap lines when converting HTML back to MD

---

myhpi/templates/base.html

Requesting the German version `/de` now sets the `<html lang="de">` language. Closes #494

Match HTML lang to user preference

---

myhpi/polls/models.py
myhpi/tests/polls/test_ranked_choice_algorithm.py

As described by @lukasrad02, the current algorithm for ranked choice elections throws an exception if there is an empty ballot (i.e., a voter who ranked no choice but still submitted their ballot). I've fixed this error and implemented a test to check the behaviour.
For reference: Here is where it previously broke
```
======================================================================
ERROR: test_empty_ballots (myhpi.tests.polls.test_ranked_choice_algorithm.RankedChoiceAlgorithmTests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/beb/code/fsr/myHPI/myhpi/tests/polls/test_ranked_choice_algorithm.py", line 117, in test_empty_ballots
self.poll.calculate_ranking(),
File …
```

Deal with Empty Ballots (And Test Correct Behaviour)

---

myhpi/core/models.py
myhpi/core/templates/core/minutes_list.html
myhpi/core/templatetags/minutes_tags.py
myhpi/locale/de/LC_MESSAGES/django.po

Closes #193 
This adds year based pagination for minutes lists. By default, the year with the newest minutes is shown (if there are no minutes at all, the current year is shown).
I looks approximately like this:
If there are no more years in any direction, the `...` disappear` and if the smallest / largest year is selected, the arrow-button is disabled:

feature(minutes): add year-based pagination

---

myhpi/static/scss/footer.scss
myhpi/templates/footer.html
myhpi/urls.py

Closes #559 
Using the set language view from Django: https://docs.djangoproject.com/en/5.0/topics/i18n/translation/#the-set-language-redirect-view, integrated into the existing links.
Using a form with hidden fields to achieve that.

Set language cookie when selecting language

---

myhpi/static/css/myHPI_admin.css

Fixes the main issues in dark mode addressed in #421 
This is not the nicest solution, but it helps us with working in the myHPI dark mode admin panel for now

Quick-Fix for broken selectors in admin dark mode

---

myhpi/search/templates/search/search_result.html
myhpi/search/templatetags/search.py
myhpi/search/views.py
myhpi/static/scss/myHPI.scss

This is a PR to track some improvements to the search page. This includes proper sorting, a better content preview and maybe additional filters.

Improve search results page

---

.pre-commit-config.yaml
.prettierrc
README.md
myhpi/core/templates/core/information_page.html
myhpi/core/templates/core/minutes.html
myhpi/core/templates/core/sidebar.html
myhpi/core/templates/core/toc_button.html
myhpi/core/templatetags/core_extras.py
myhpi/search/templates/search/search_field.html
myhpi/settings.py
myhpi/static/js/myHPI.js
myhpi/static/js/navbar.js
myhpi/static/js/sidebar.js
myhpi/static/scss/myHPI.scss
myhpi/templates/base.html
poetry.lock
pyproject.toml

Closes #275, closes #329, closes #53
Replaces stale #285

Responsive Meta Panel

---

myhpi/core/templates/core/minutes_list.html
myhpi/polls/templates/polls/base_poll.html
myhpi/polls/templates/polls/poll_list.html
myhpi/static/js/myHPI.js
myhpi/static/js/navbar.js
myhpi/static/scss/myHPI.scss
myhpi/static/scss/navbar.scss

Responsive design for polls

---

myhpi/static/scss/myHPI.scss

Close #587 
Known limitation: The sidebar can overlay the toc button. This can become apparent on mobile if the sidebar/footer is so long, that the user could scroll past that point. This is not expected to be the case often. Future releases may want to move more content into offcanvas panels (like already done with the toc), which reduces the height of the sidebar further.

Ensure correct overlay order of content, toc and side panel

---

myhpi/tenca_django/views.py

In our production instance, there are some mailing lists that have not been created with tenca and thus are lacking the tenca hash id. This causes an error on the server when somebody who is member of such a list visits the dashboard.
This PR sets a new flag when querying the lists from tenca to prevent the error to be raised.

Ignore lists with missing hashes on the dashboard

---

README.md
myhpi/core/templates/core/information_page.html
myhpi/core/templates/core/minutes.html
myhpi/core/templates/core/sidebar.html
myhpi/core/templates/core/toc_button.html
myhpi/locale/de/LC_MESSAGES/django.po

Closes #606 
Should eventually be fixed properly by #609

fix: hot fix toc button display with attachments and no toc

---

.github/workflows/tests.yml

Fixes GitHub pipeline by actually using djLint instead of djhtml

fix: use djLint instead of djhtml in GitHub job

---

.github/workflows/tests.yml

20.04 is deprecated and actions do not work anymore (see https://github.com/fsr-de/myHPI/actions/runs/15391157277/job/43317974106)
See also: https://github.com/actions/runner-images/issues/11101

Bump Ubuntu version in GH Action runner
